### ISSUE TITLE
Missing numbers in drawing dimensioning preference setting.

### ISSUE THREAD

**Issue by iaminfinite** [hamish2014/FreeCAD_drawing_dimensioning#51]
Can't see variable numbers in Edit > Preference > Drawing dimensioning, as shown in attached image. But seem like plus and minus buttons works.
![drawing dimensioning](https://cloud.githubusercontent.com/assets/8560529/8546075/c65723d4-24de-11e5-9138-d4b41af3fee4.png)
FreeCAD 0.15 rev 4671 on Fedora 22

**Comment by hamish2014** [comment]
Hi iaminfinite, thanks for the posting the issue.
Question: are variable numbers only missing for *Edit>Preference>Drawing dimensioning* or are they also missing in other preference tabs as well, such as  *Edit>Preference>General*?

**Comment by iaminfinite** [comment]
Hamish,

All others work fine, but Drawing dimensioning.

**Comment by hamish2014** [comment]
Ai, I really do not know what the cause of your issue is.
On both my Windows and Ubuntu Linux FreeCAD's i do not experience the problem.
The Resources/ui/drawing_dimensioing_prefs-base.ui file is edited using Qt designer 4, do you think that is the cause the problem?
So i am afraid I can't be of much help.

In the mean while, adjust your dimensioning preference in the FreeCAD task dialog panel, as you create dimensions.
Changing the preferences there will have the same effect as changing them in Edit>Preferences
