### ISSUE TITLE
Multiple grab points on single line

### ISSUE THREAD

**Issue by arkticrainbow** [hamish2014/FreeCAD_drawing_dimensioning#62]
I got a question - maybe a bug. When I want to dimension create dimension on some object, there is multiple dots appearing for a single line, see image below:

![multi2](https://cloud.githubusercontent.com/assets/13998246/9568948/7a0b3a8c-4f5a-11e5-979a-043574d43c00.png)

I dont understand why so many grab points are created. I find it frustrating when I am having chamfer and need to grab the edges of it. I have to zoom in to find the grab point on the very edge of the line and than zoom out a whole lot to get to the other point.

![multi3](https://cloud.githubusercontent.com/assets/13998246/9568965/d23b4a26-4f5a-11e5-9871-b8ee2bf75d6c.png)

Some other times mainly when I create not so complex shapes this doesnt happen. Is it as it suppose to be or is there something I can make about it?

**Comment by hamish2014** [comment]
I appreciate your frustration, but the multiple dots originate from the drawing workbench.
In particular, the drawing dimensioning workbench parses the Svgs created by the drawing workbench.
In the case mentioned, the Svg created has multiple lines instead of just one straight line.
For the drawing workbench, I suspect that breaking the circular edge up into multiple lines helps with generating the drawing views ...

**Comment by arkticrainbow** [comment]
Fair enough than. Thanks for reply.
