### ISSUE TITLE
Preferences Page UI suggestions

### ISSUE THREAD

**Issue by triplus** [hamish2014/FreeCAD_drawing_dimensioning#9]
Nice job on new Preferences page!

I noticed two things:

* Preferences text (example preference font size) could start with capital letter.
* Drawing Dimensioning text and linearDimension icon in Preferences sidebar overlap.  The linearDimension icon size could be smaller and/or text could be changed just to Dimensioning.

**Comment by hamish2014** [comment]
Hi Triplus,

Thank you for your comments, but I am going leave things as they are for the moment:
* capatilization is just a matter of personal taste.
* the icon in the preferences page must be labelled `drawing dimensioning' because a dimensioning workbench already exists. The icon is streched in the freecad preferences window as to match the width of the text; this behaviour is out-of-my control. So although I am also slight frustrated with it, I am going to leave is.
